steps:
# Deploy an image from Container Registry to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'railsproto'
  - '--image'
  - 'gcr.io/rails-container-prototype/rails_proto'
  - '--region'
  - 'asia-northeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
# gcloud builds submit --tag gcr.io/rails-container-prototype/rails_proto
# gcloud run deploy railsproto --image gcr.io/rails-container-prototype/rails_proto --platform managed