steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/rails-container-prototype/rails_proto',
         '--file=./Dockerfile.production',
         '--build-arg', '_RAILS_MASTER_KEY=$_RAILS_MASTER_KEY',
         '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/rails-container-prototype/rails_proto']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'railsproto', '--image', 'gcr.io/rails-container-prototype/rails_proto', '--region', 'asia-northeast1', '--platform', 'managed']
images:
- gcr.io/rails-container-prototype/rails_proto

# 実行コマンド: gcloud builds submit