default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  user: postgres
  password: regex-posgre
  database: rails_proto_production
  host: /cloudsql/rails-container-prototype:asia-northeast1:regex